{
 "title": "SRE - Project 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency (90th percentile response time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(flask_http_request_duration_seconds_bucket{job=\"ec2\"}[5m])) by (le,method))"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{job=\"ec2\",status=~\"2..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{job=\"ec2\",status=~\"2..\"}[5m]))/sum(rate(flask_http_request_total{job=\"ec2\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "20% Remaining Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((1 - (sum(increase(flask_http_request_total{job=\"ec2\",status=~\"2..\"}[5m])) by (method)) / sum(increase(flask_http_request_total{job=\"ec2\"}[5m])) by (method)) / (1 - .80))"
    }
   ]
  }
 ]
}